-- Overturn Spy — bundle header
-- This file is prepended to every bundled output by scripts/bundle.py.
-- It documents the build and establishes the module scope preamble.

--[[
  ╔══════════════════════════════════════════════════════════════╗
  ║              Overturn Spy  v2.0.0                           ║
  ║              Purple/matte-black Roblox Remote Spy           ║
  ║              https://github.com/burningtire1/Overturn-Spy   ║
  ╚══════════════════════════════════════════════════════════════╝

  AUTO-GENERATED — do not edit this file directly.
  Run  python scripts/bundle.py  to rebuild from src/.
]]
